# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Crosscompile RICv2 for Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
      contents: write

jobs:
  build_add_to_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
    - name: Install dependencies
      run: go get .
    - name: Build RICv2_linux_amd64
      run: GOOS=linux GOARCH=amd64 go build -o RICv2_linux_amd64 -v ./... 
    - name: Build RICv2_linux_arm64
      run: GOOS=linux GOARCH=arm64 go build -o RICv2_linux_arm64 -v ./... 
    - name: Build RICv2_linux_arm
      run: GOOS=linux GOARCH=arm go build -o RICv2_linux_arm -v ./... 
    - name: Build RICv2_windows_amd64
      run: GOOS=windows GOARCH=amd64 go build -o RICv2_windows_amd64 -v ./... 
    - name: Release with Notes
      uses: softprops/action-gh-release@v2
      with:
        files: |
          RICv2_*
          
